import { chromium } from '@playwright/test'
const b = await chromium.launch({ args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] })
const p = await b.newPage({ viewport:{width:1280,height:800} })
await p.goto('http://localhost:4173')
await p.getByRole('button',{name:'God Mode'}).click()
await p.getByTestId('speed-60').click()
await p.waitForTimeout(6000)
await p.screenshot({ path:'/home/benbatya/.claude/jobs/db2d8d1c/tmp/m2.png' })
console.log('SIM', JSON.stringify(await p.evaluate(()=>window.__SIM__)))
await b.close()
