import { chromium } from '@playwright/test'
const b = await chromium.launch({ args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] })
const p = await b.newPage({ viewport:{width:1360,height:820} })
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); p.on('pageerror',e=>errs.push(String(e)))
await p.goto('http://localhost:4173')
await p.getByTestId('speed-60').click()
await p.waitForTimeout(9000)
await p.getByRole('button',{name:'God Mode'}).click(); await p.waitForTimeout(500)
await p.screenshot({ path:'/home/benbatya/.claude/jobs/db2d8d1c/tmp/fix_god.png' })
await p.getByRole('button',{name:'User Console'}).click(); await p.waitForTimeout(500)
await p.screenshot({ path:'/home/benbatya/.claude/jobs/db2d8d1c/tmp/fix_console.png' })
console.log('ERRORS', errs.length, errs.slice(0,3).join(' | '))
await b.close()
